services:
  - type: web
    name: fitness-ai-service
    env: python
    region: oregon  # Choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        sync: false  # This will be set manually in Render dashboard
      - key: PYTHONUNBUFFERED
        value: true
    autoDeploy: true
    numInstances: 1
    plan: starter  # Choose appropriate plan based on your needs 